### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by CraigSubnarine** [uwidcit/AgriMarketWatcher#3]
1) The resource https://agrimarketwatch.herokuapp.com/crops/daily/recent (Line 10 services.js) is not bringing up the most resent information from the date resource https://agrimarketwatch.herokuapp.com/crops/daily/dates.

2) The https://agrimarketwatch.herokuapp.com/crops/predict resource (Line 43 services.js) not found (404 Error).

**Comment by kyledef** [comment]
Issue was fixed
